gpu_number: 1
seed: 1234
save_model: False

wandb:
  project: "mamba-research"
  group: "yelp_reviews"
  name: "embeddings, period=50, tokens=100"

model:
  name: "state-spaces/mamba-130m"
  period: 50
  tokens_num: 100

training_type: "embeddings"

training:
  batch_size: 16
  epochs: 3
  learning_rate: 0.001
  warmup_percent: 0.05
