gpu_number: 4
seed: 1234
save_model: False

wandb:
  project: "mamba-research"
  group: "yelp_reviews"
  name: "embeddings, period=-1, tokens=1"

model:
  name: "state-spaces/mamba-130m"
  period: -1
  tokens_num: 1

training_type: "embeddings"

training:
  test_batch_size: 16
  batch_size: 16
  accumulation_steps: 1
  epochs: 3
  learning_rate: 0.001
  warmup_percent: 0.05
