gpu_number: 1
seed: 1234
save_model: False

wandb:
  project: "mamba-research"
  group: "yelp_reviews"
  name: "embeddings, period=50, tokens=200"

model:
  name: "state-spaces/mamba-130m"
  period: 50
  tokens_num: 200

training_type: "embeddings"

training:
  test_batch_size: 16
  batch_size: 8
  accumulation_steps: 2
  epochs: 3
  learning_rate: 0.001
  warmup_percent: 0.05
